[package]
name = "pari-gp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A gp! macro that internally runs PARI/GP code and converts to and from GP syntax"
categories = ["mathematics"]
keywords = ["pari-gp", "proc-macro", "math", "number-theory"]

[dependencies]
gp-macro = { path = "../gp-macro", version = "0.1.1" }
gp-runtime = { path = "../gp-runtime", version = "0.1.1" }

[dev-dependencies]
num-rational = "0.4.2"
